spring:
  application:
    name: melikyan-academy

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/melikyan_academy
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true